### ISSUE TITLE
안드로이드 Screen orientation 전환 시 오류

### ISSUE THREAD

**Issue by RelaxBacteria** [SausageTaste/Little-Ruler#1]
테스트 기기: Galaxy S10, Android Nougat.

앱을 실행하고 화면을 전환하면 물이 문어 먹물처럼 시꺼매지거나 튕깁니다.
가로로 고정하는게 낫겠습니다.

빨리 ㄱㄱ

**Comment by SausageTaste** [comment]
일단 지금은 화면 해상도 변경에 따라 화면 상의 위젯들이 올바르게 리사이징 되는 거 테스트 하느라 화면 회전 허용해 놨음. 내 폰에는 그런 문제 없는데 오히려 최신 폰에서 그런 문제가 생기네. ㄷㄷ 어쨌든 이따 집에 가서 새로 빌드해서 구글 드라이브에 올리겠음.

**Comment by SausageTaste** [comment]
아니 근데 이슈 올라오면 메일로 알림이라도 좀 주지 이걸 이제야 봤네. ㅋㅋㅋ

**Comment by SausageTaste** [comment]
최신 빌드 apk로 구글드라이브에 업로드해 놓음. 물리기반렌더링 적용, 안드로이드에서 화면 회전 막음, 낮은 각도에서 수면 이미지가 왜곡되는 현상 완화, 수면의 먼 곳에 검은 줄무늬 생기는 문제 해결 등.
시험기간 + 물리기반렌더링의 어려움 때문에 진전이 별로 없네. ㅜㅜ

**Comment by RelaxBacteria** [comment]
어렵지, 수고한다. 그런데 말이야, 안드로이드 버전의 이슈를 하나 더 발견했어ㅋㅋㅋ.

**Comment by SausageTaste** [comment]
머
