### ISSUE TITLE
little-ruler_0.2.0_win_x64.zip

### ISSUE THREAD

**Issue by RelaxBacteria** [SausageTaste/Little-Ruler#8]
[log_2020-04-27_10-21.txt](https://github.com/SausageTaste/Little-Ruler/files/4536886/log_2020-04-27_10-21.txt)
구동이 안됩니다.ㅠㅠ

구동환경: XNOTE A520 WINDOWS 10
그래픽카드‎: ‎NVIDIA® GeForce™ GT 540M	OS(운영체제)‎: ‎정품 Windows®10
메모리‎: ‎DDR3 1333MHz (4 GB×2)	CPU‎: ‎2세대 인텔® 코어™ i7 쿼드 프로세서 2820QM

**Comment by SausageTaste** [comment]
네 컴퓨터의 내장 그래픽 장치(CPU)가 OpenGL 3.3을 지원하지 않아서 그런 것 같다.
내 프로그램은 현재 기본값으로 내장 그래픽 장치를 쓰도록 돼 있음.

그러니 수동으로 Nvidia의 그래픽 장치를 쓰도록 하면 될 거임.
exe파일 우클릭 하면 뜨는 메뉴에 `Run with graphics processor`라는 메뉴가 있으면 그 안에 `High performance NVIDIA processor` 눌러서 실행해봐.

다음 업데이트에서는 그래픽 드라이버 지원 여부 확인하는 기능도 넣어야겠다.

![2020-04-28 (3)](https://user-images.githubusercontent.com/23379360/80468205-dcff7a00-8979-11ea-9a32-72aabad81cfa.png)

**Comment by SausageTaste** [comment]
CMake로 generate 할 때 GLFW_USE_HYBRID_HPG 쓰면 자동으로 외장 GPU를 사용한다.
대부분의 경우 이 정도면 충분하겠지.
